import { useLoaderData } from "react-router";
import { boundary } from "@shopify/shopify-app-react-router/server";
import { authenticate } from "../shopify.server";
import prisma from "../db.server";

export const loader = async ({ request }) => {
  const { session } = await authenticate.admin(request);
  const store = await prisma.store.findUnique({ where: { shop: session.shop } });
  return { store };
};

function StatCard({ label, value, sub }) {
  return (
    <div className="rounded-2xl border border-neutral-200 bg-white p-5">
      <p className="text-sm text-neutral-500">{label}</p>
      <p className="mt-1 text-2xl font-semibold text-neutral-900">{value}</p>
      {sub && <p className="mt-1 text-xs text-neutral-400">{sub}</p>}
    </div>
  );
}

function StepCard({ number, title, children }) {
  return (
    <div className="flex gap-4 rounded-2xl border border-neutral-200 bg-white p-5">
      <div className="flex h-8 w-8 flex-none items-center justify-center rounded-full bg-neutral-900 text-sm font-semibold text-white">
        {number}
      </div>
      <div>
        <p className="font-semibold text-neutral-900">{title}</p>
        <p className="mt-1 text-sm text-neutral-500">{children}</p>
      </div>
    </div>
  );
}

export default function Index() {
  const { store } = useLoaderData();

  const daysLeftInTrial = store?.trialEndsAt
    ? Math.max(0, Math.ceil((new Date(store.trialEndsAt) - new Date()) / 86400000))
    : null;

  return (
    <div className="mx-auto max-w-5xl px-6 py-10">
      <div className="flex items-center justify-between">
        <div>
          <p className="text-sm font-medium text-neutral-400">LetsWearIt</p>
          <h1 className="mt-1 text-2xl font-semibold text-neutral-900">
            AI Try-On
          </h1>
        </div>
        {store?.subscriptionStatus === "trial" && daysLeftInTrial !== null && (
          <span className="rounded-full bg-amber-50 px-3 py-1.5 text-sm font-medium text-amber-700">
            {daysLeftInTrial} day{daysLeftInTrial === 1 ? "" : "s"} left in trial
          </span>
        )}
      </div>

      <p className="mt-3 max-w-2xl text-sm text-neutral-500">
        Let customers see how a product looks on them before they buy. Upload
        reference photos for a product and a floating{" "}
        <span className="font-medium text-neutral-700">Try It On</span>{" "}
        button appears on that product's storefront page automatically.
      </p>

      {store && (
        <div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-3">
          <StatCard
            label="Plan"
            value={store.planKey === "trial" ? "Free trial" : store.planKey}
          />
          <StatCard
            label="Generations used"
            value={`${store.generationsUsed} / ${store.generationLimit}`}
            sub="resets each billing period"
          />
          <StatCard
            label="Status"
            value={store.subscriptionStatus}
          />
        </div>
      )}

      <h2 className="mt-10 text-lg font-semibold text-neutral-900">
        How it works
      </h2>
      <div className="mt-4 grid grid-cols-1 gap-4">
        <StepCard number={1} title="Add reference photos">
          Go to <a href="/app/products" className="underline">Products</a>,
          open any product, and upload a front, back, and side photo. This
          writes each image to that product as a metafield — no theme
          editing required.
        </StepCard>
        <StepCard number={2} title="Widget appears automatically">
          Any product with a front photo saved shows the "Try It On" button
          on its storefront page. Turn it on once under{" "}
          <span className="font-medium">Theme Editor → App embeds</span>.
        </StepCard>
        <StepCard number={3} title="Customer tries it on">
          They upload their own photo (or use a sample), tap Generate, and
          see themselves wearing the product — front, side, and back —
          generated by Gemini in a few seconds.
        </StepCard>
        <StepCard number={4} title="Track usage and stay covered">
          Every generation counts against your plan's monthly limit. Check{" "}
          <a href="/app/billing" className="underline">Billing</a> anytime to
          see usage or change plans, and we'll email you automatically at 80%
          and 100% of your limit.
        </StepCard>
      </div>

      <div className="mt-10 flex gap-3">
        <a
          href="/app/products"
          className="rounded-full bg-neutral-900 px-5 py-2.5 text-sm font-semibold text-white hover:bg-neutral-800"
        >
          Add your first product
        </a>
        <a
          href="/app/billing"
          className="rounded-full border border-neutral-300 px-5 py-2.5 text-sm font-semibold text-neutral-700 hover:bg-neutral-100"
        >
          View plans
        </a>
      </div>
    </div>
  );
}

export const headers = (headersArgs) => {
  return boundary.headers(headersArgs);
};